name: PR
on:
  pull_request:

jobs:
  sync:
    name: "ECR Sync"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install
      - run: npm run build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Cleanup foobar/nginx repo
        run: |
          aws ecr list-images --registry-id ${{ secrets.AWS_ECR_REGISTRY_ID }} --repository-name foobar/nginx --no-paginate > images.json
          aws ecr batch-delete-image --registry-id ${{ secrets.AWS_ECR_REGISTRY_ID }} --repository-name foobar/nginx --no-paginate --cli-input-json file://images.json
          rm images.json
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: "${{ secrets.AWS_ECR_REGISTRY_ID }}"
      - name: Sync repos
        uses: ./
        with:
          ecr_registry: ${{ secrets.AWS_ECR_REGISTRY_ID }}.dkr.ecr.eu-central-1.amazonaws.com
          repo_file: ./example/repos.json
          tag_limit: 10
